### PR TITLE
fix broken travis

### PR DESCRIPTION
**Pull request by tklebel**

### CODE REVIEW

**Comment by tklebel** [comment]
Quite shamefully didn't read what you already tried properly, regarding your question on SO.

**Comment by cormac85** [comment]
@tklebel Yeah I was still actively changing the .travis.yml file to try to get it fixed.  

Funnily enough your attempted merge got me thinking about my choice of packrat for the package installation, so I just pulled it out and went for the default `cache:  packages` and it seems the `loadVignetteBuilder()` was able to find `knitr`.   

I'm still not sure if this was an issue specific to my build or a bug in the R side of Travis-CI. I set it up as was [suggested in the docs](https://docs.travis-ci.com/user/languages/r/#Packrat) so...

**Comment by tklebel** [comment]
That's great! I thought about asking, why packrat would be necessary, but I figured it was not mine to judge that.

I generally found packrat not very intuitive or easy to deal with upfront, but using it within package development together with travis probably needs quite a deep understanding of how `R CMD check` works both locally and on travis, from which I am very far away...

**Comment by cormac85** [comment]
I guess packrat isn't necessary, but it did seem to knock a couple minutes off the Travis build time, which is hardly a constraint for me at this stage so it's no big loss.

>   a deep understanding of how R CMD check works both locally and on travis, from which I am very far away...

You and me both!

Edit: Oh and thanks for taking time to look at this, much appreciated!

**Comment by tklebel** [comment]
If it's just for Travis build time, it seems rather cumbersome to put up with packrat.
Anyways, I'm glad I was of some help!

**Pull request closed without merging**
